# How many logbook problems are classified as cracked?

PREFIX : <https://w3id.org/zorro#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT (COUNT(?problem) AS ?crackedCount)
WHERE {
    ?problem rdf:type :CrackedProblem .
}
