# Which 10 parts are most frequently involved in logbook problem reports?

PREFIX : <https://w3id.org/zorro#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?part (COUNT(?problem) AS ?problemFrequency)
WHERE {
    ?problem :involves ?part .
}
GROUP BY ?part
ORDER BY DESC(?problemFrequency)
LIMIT 10
