# What functions does the function X depend on?

PREFIX : <https://w3id.org/zorro#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?function ?dependency
WHERE {
    BIND(:HousingAndSupportingCombustion AS ?function)
    ?function :dependsOn ?dependency .
}
