
# What is the frequency of all the problem type at each location (which Cylinder or 
# Engine)?
SELECT ?problemType ?location (COUNT(?p) AS ?Frequency)
WHERE {
    ?p rdf:type ?problemType ;
       :atLocation ?location .
}
GROUP BY ?problemType ?location
ORDER BY DESC(?Frequency)
