# Which problems share the same cause?

PREFIX : <https://w3id.org/zorro#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?cause (GROUP_CONCAT(DISTINCT ?problem; separator=", ") AS ?problemList)
       (COUNT(DISTINCT ?problem) AS ?problemCount)
WHERE {
    ?problem :hasCause ?cause .
}
GROUP BY ?cause
HAVING (COUNT(DISTINCT ?problem) > 1)
ORDER BY DESC(?problemCount)
