# Which parts fail most often?
PREFIX base: <https://w3id.org/zorro#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

SELECT ?partlabel (COUNT(?problem) AS ?frequency)
WHERE {
?event base:hasProblem ?problem.
?problem base:involves ?part.
?part rdfs:label ?partlabel.
}
GROUP BY ?partlabel
ORDER BY DESC(?frequency)
LIMIT 10