# Which causes are documented for the problem "Low Oil Pressure"?

PREFIX : <https://w3id.org/zorro#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?problem ?cause
WHERE {
    BIND(:LowOilPressure AS ?problem)
    ?problem :hasCause ?cause .
}
