# Which functions ultimately depend on the functions of the Power Section?

PREFIX : <https://w3id.org/zorro#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT DISTINCT ?dependentFunction ?dependentFunctionLabel
WHERE {
    BIND(:PowerSection AS ?system)
    ?system :hasFunction ?function .
    ?dependentFunction :dependsOn+ ?function ;
                       rdf:type :Function ;
                       rdfs:label ?dependentFunctionLabel .
}
